In [12]:
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import RandomizedSearchCV

In [13]:
df = pd.read_csv('Training.csv',on_bad_lines='skip',low_memory=False)

In [14]:
df.dropna()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           0          0                     0                    0   
1           0          0                     0                    0   
2           0          0                     0                    0   
3           0          0                     0                    0   
4           0          0                     0                    0   
...       ...        ...                   ...                  ...   
5045        0          0                     0                    0   
5046        0          0                     0                    0   
5047        0          0                     0                    0   
5048        0          0                     0                    0   
5049        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
5045          0       0           0             0        0                 0   
5046          0       0           0             0        0                 0   
5047          0       0           0             0        0                 0   
5048          0       0           0             0        0                 0   
5049          0       0           0             0        0                 0   

      ...  irregular_heart_sound  decrease_alertness  chest_discomfort  \
0     ...                      0                   0                 0   
1     ...                      0                   0                 0   
2     ...                      0                   0                 0   
3     ...                      0                   0                 0   
4     ...                      0                   0                 0   
...   ...                    ...                 ...               ...   
5045  ...                      0                   0                 0   
5046  ...                      0                   0                 0   
5047  ...                      0                   0                 0   
5048  ...                      0                   0                 0   
5049  ...                      0                   0                 0   

      irregular_heart_beat  heart_murmur  arm_pain  stroke  fainting  \
0                        0             0         0       0         0   
1                        0             0         0       0         0   
2                        0             0         0       0         0   
3                        0             0         0       0         0   
4                        0             0         0       0         0   
...                    ...           ...       ...     ...       ...   
5045                     0             0         0       0         0   
5046                     0             0         0       0         0   
5047                     0             0         0       0         0   
5048                     0             0         0       0         0   
5049                     0             0         0       0         0   

      shortness_of_breath                                prognosis  
0                       0  (vertigo) Paroymsal  Positional Vertigo  
1                       0  (vertigo) Paroymsal  Positional Vertigo  
2                       0  (vertigo) Paroymsal  Positional Vertigo  
3                       0  (vertigo) Paroymsal  Positional Vertigo  
4                       0  (vertigo) Paroymsal  Positional Vertigo  
...                   ..

In [15]:
df.isnull().values.any()

False

In [16]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        0          0                     0                    0          0   
1        0          0                     0                    0          0   
2        0          0                     0                    0          0   
3        0          0                     0                    0          0   
4        0          0                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   irregular_heart_sound  decrease_alertness  chest_discomfort  \
0                      0                   0                 0   
1                      0                   0                 0   
2                      0                   0                 0   
3                      0                   0                 0   
4                      0                   0                 0   

   irregular_heart_beat  heart_murmur  arm_pain  stroke  fainting  \
0                     0             0         0       0         0   
1                     0             0         0       0         0   
2                     0             0         0       0         0   
3                     0             0         0       0         0   
4                     0             0         0       0         0   

   shortness_of_breath                                prognosis  
0                    0  (vertigo) Paroymsal  Positional Vertigo  
1                    0  (vertigo) Paroymsal  Positional Vertigo  
2                    0  (vertigo) Paroymsal  Positional Vertigo  
3                    0  (vertigo) Paroymsal  Positional Vertigo  
4                    0  (vertigo) Paroymsal  Positional Vertigo  

[5 rows x 143 columns]

In [17]:
df['prognosis'].unique()

array(['(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'AIDS',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'Gastroenteritis', 'GERD', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins',
       'Hypertensive Heart Disease', 'Ischaemic Heart Disease',
       'Valvular Heart Disease', 'Cardiomyopathy',
       'Congestive Heart Failure', 'Atrial Fibrillation',
       'Mitral Valve Regurgitation', 'Mitral Valve stenos

In [18]:
encoder = LabelEncoder()
df["prognosis"] = encoder.fit_transform(df["prognosis"])
df = df.sample(frac=1).reset_index(drop=True)
#Y
Y = df['prognosis']
Y = np.asarray(Y)
#X 
X =df.drop(['prognosis'], axis=1)
X = np.asarray(X)

print(X.shape)
print(Y.shape)

(5050, 142)
(5050,)


In [19]:
x_train, x_test,y_train, y_test = train_test_split(X,Y ,random_state=42, test_size=0.2, shuffle=True)

In [25]:
n_estimators = np.linspace(100, 1000, 100, dtype=int)
max_depth = [1, 5, 10, 20, 50, 75, 100, 150, 200]
min_samples_split = [1, 2, 5, 10, 15, 20, 30]
min_samples_leaf = [1, 2, 3, 4]
bootstrap = [True, False]

criterion=['gini', 'entropy']
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
               'criterion': criterion}

In [ ]:
rf_base = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf_base,param_distributions = random_grid,verbose=2,random_state=42)
rf_random.fit(x_train, y_train)

In [27]:
rf_random.best_params_

{'n_estimators': 963,
 'min_samples_split': 10,
 'min_samples_leaf': 3,
 'max_depth': 75,
 'criterion': 'gini',
 'bootstrap': True}

In [28]:
clf = RandomForestClassifier(n_estimators=963,min_samples_split= 10,min_samples_leaf=3,max_depth= 75,criterion='gini',bootstrap= True )
clf.fit(x_train,y_train)
pred=clf.predict(x_test) 

In [29]:
result = confusion_matrix(y_test, pred)

In [30]:
print('Matrix: ')
print(result)

Matrix: 
[[20  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  0  0]
 [ 0  0  0 ...  0 23  0]
 [ 0  0  0 ...  0  0 23]]


In [31]:
result1 = classification_report(y_test, pred)
print('Report:')
print (result1)

Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        26
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00        24
           4       1.00      1.00      1.00        25
           5       1.00      1.00      1.00        16
           6       0.67      1.00      0.80         2
           7       1.00      1.00      1.00        27
           8       1.00      1.00      1.00         6
           9       1.00      1.00      1.00        34
          10       1.00      1.00      1.00        27
          11       1.00      1.00      1.00        29
          12       1.00      1.00      1.00        13
          13       1.00      0.71      0.83         7
          14       1.00      1.00      1.00        22
          15       1.00      1.00      1.00        26
          16       1.00      1.00      1.00        27
          17       

In [32]:
result2 = accuracy_score(y_test,pred)
print("Accuracy",result2)

Accuracy 0.9930693069306931
